package-name: airflow-provider-kaggle

display-name: Kaggle

docs_url: https://github.com/sp1thas/airflow-provider-kaggle/blob/main/README.md

hooks:
  - module: kaggle_provider.hooks.kaggle.KaggleHook

operators:
  - module: kaggle_provider.operators.kaggle.KaggleOperator
